### ISSUE TITLE
Check "get notified on update of this addon" by default?

### ISSUE THREAD

**Issue by Noitidart** [jvillalobos/AMO-Admin-Assistant#12]
Hey Jorge are you accepting PRs on this? What do you think about an option on this addon that forces checking the "Notify me the next time this add-on is updated. (Subsequent updates will not generate an email)" by default?

I am forgetting to check that a lot.

**Comment by jvillalobos** [comment]
I accept PRs, but I don't think this is a feature most of the users of this add-on would like. I think it's okay to have it behind a hidden pref, if you want to send the PR for that.

**Comment by Noitidart** [comment]
Ah ok thanks :)

**Comment by Noitidart** [comment]
I was hoping to add this in to the WebExt version. But they don't have prefs.  So I was thinking of doing this:

create file at simple-storage location: profileDir / jetpack / addon_id / simple-storage / prefs.json

And then on uninstall of addon it would delete the addon_id dir. Would this be cool with you? I can go any other way you prefer :)

**Comment by jvillalobos** [comment]
WebExtensions can't create files, can they? There are storage APIs, but I'm not sure what their current state is.

**Comment by Noitidart** [comment]
Oh shoot you're right. I'll look into that storage api :)
