### ISSUE TITLE
XHR is not defined - Firefox addon

### ISSUE THREAD

**Issue by tsriram** [jvillalobos/AMO-Admin-Assistant#14]
Is XMLHttpRequest supposed to work from a background page in Firefox addon? I'm trying to do an XHR to post data to Google Analytics as explained [here](https://blog.mozilla.org/addons/2016/05/31/using-google-analytics-in-extensions/) and I'm getting an error that XMLHttpRequest is not defined. Would appreciate any help!

**Comment by jvillalobos** [comment]
https://developer.mozilla.org/en-US/Add-ons#Contact_us
