### ISSUE TITLE
DXR hook does not work for ajaxy results

### ISSUE THREAD

**Issue by wagnerand** [jvillalobos/AMO-Admin-Assistant#18]
DXR behaves different when loading results as in further results are loaded when scrolling to the bottom of the page. For those results, no additional links are injected.

**Comment by jvillalobos** [comment]
Yeah, there's a mutation observer that should be catching those loads, but it seems to be failing in some cases.

**Comment by jvillalobos** [comment]
Fixed in legacy branch.
